# Generated by Django 4.1.7 on 2023-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="Anonymous", max_length=50),
        ),
    ]
