# Generated by Django 4.1.7 on 2023-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
        ("accounts", "0003_alter_customuser_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tags",
            field=models.ManyToManyField(to="tag.tag"),
        ),
    ]
