# Generated by Django 4.1.7 on 2023-02-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="create_by",
            new_name="created_by",
        ),
    ]
