# Generated by Django 4.1.7 on 2023-02-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="contributor",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
