# Generated by Django 4.1.7 on 2023-02-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="canvas",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="note.canvas"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="note/"),
        ),
    ]
