# Generated by Django 4.1.7 on 2023-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0002_rename_create_at_note_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
