# Generated by Django 4.1.7 on 2023-02-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0003_alter_note_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.IntegerField()),
                ("handwriting", models.ImageField(upload_to="")),
                ("background", models.ImageField(upload_to="")),
                (
                    "canvas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="note.canvas"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="note",
            name="canvas",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="note.canvas"
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
