# Generated by Django 4.1.7 on 2023-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0004_page_alter_note_canvas_delete_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="handwriting",
        ),
        migrations.AlterField(
            model_name="page",
            name="background",
            field=models.ImageField(null=True, upload_to="note/"),
        ),
    ]
