# Generated by Django 4.1.7 on 2023-02-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0005_remove_page_handwriting_alter_page_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="canvas",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="note.canvas",
            ),
        ),
    ]
