# Generated by Django 4.1.7 on 2023-02-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0006_alter_page_canvas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="canvas",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="note.canvas"
            ),
        ),
    ]
